.\" best(1) manpage
.\"
.\" Copyright (C) 2005 Novell, Inc.
.\"
.TH BEST "1" "Feb 2005" "beagle" "Linux User's Manual"
.SH NAME
best \- GNOME-based tool for searching your personal information space
.SH SYNOPSIS
.B best
[\fIoptions\fR]
.SH DESCRIPTION
.PP
.BR best
is a GNOME-based tool for searching your personal information space.
.SH OPTIONS
.BR best
has no application-specific options.  See \fIbest --help\fR for a list of
generic GNOME options.
.SH AUTHOR
Novell, Inc.
.SH "REPORTING BUGS"
Report bugs to <dashboard-hackers@gnome.org>.
.SH COPYRIGHT
Copyright \(co 2005 Novell, Inc.
.sp
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR beagled (1),
.BR beagle-query (1),
.BR beagle-status (1),
.BR beagle-shutdown (1)
