// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 1.1.4322.573
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Mono Web Services Description Language Utility
//
using System;

namespace Beagle.Daemon
{
/// <remarks/>
/// <remarks>
///Web Service Interface to Beagle
///</remarks>
[System.Web.Services.WebServiceBinding(Name="BeagleWebServiceSoap",Namespace="http://www.gnome.org/projects/beagle/webservices"),
System.Diagnostics.DebuggerStepThroughAttribute(),
System.ComponentModel.DesignerCategoryAttribute("code")]
public class BeagleWebService: System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    public BeagleWebService () {
        this.Url = "http://localhost:8888/beagle/search.asmx";
    }

	string hostname = "localhost";
	string port = "8888";
    
    public BeagleWebService (string Hostname, string Port) {
        	
    	if (Hostname == null || Hostname == "")
        	this.hostname = "localhost";
        else
        	this.hostname = Hostname;
        	
        this.Url = "http://" + this.hostname + ":" + this.port + "/beagle/search.asmx";
      	
    }
    
	public string Hostname {
		get {return hostname;}
		set {
			hostname = value;
			this.Url = "http://" + this.hostname + ":" + this.port + "/beagle/search.asmx";
		}
	}
	
	public string Port {
		get {return port;}
		set {
			port = value;
			this.Url = "http://" + this.hostname + ":" + this.port + "/beagle/search.asmx";
		}
	}
    
    /// <remarks>
    ///Full object interface to Beagle
    ///</remarks>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gnome.org/projects/beagle/webservices/BeagleQuery",RequestNamespace="http://www.gnome.org/projects/beagle/webservices",ResponseNamespace="http://www.gnome.org/projects/beagle/webservices",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public SearchResult BeagleQuery(SearchRequest req) {
        object[] results = this.Invoke("BeagleQuery", new object[] {
            req});
        return ((SearchResult)(results[0]));
    }
    
    public System.IAsyncResult BeginBeagleQuery(SearchRequest req, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("BeagleQuery", new object[] {
            req}, callback, asyncState);
    }
    
    public SearchResult EndBeagleQuery(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SearchResult)(results[0]));
    }
    
    /// <remarks>
    ///Simple Interface to Beagle
    ///</remarks>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gnome.org/projects/beagle/webservices/SimpleQuery",RequestNamespace="http://www.gnome.org/projects/beagle/webservices",ResponseNamespace="http://www.gnome.org/projects/beagle/webservices",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public SearchResult SimpleQuery(string text) {
        object[] results = this.Invoke("SimpleQuery", new object[] {
            text});
        return ((SearchResult)(results[0]));
    }
    
    public System.IAsyncResult BeginSimpleQuery(string text, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SimpleQuery", new object[] {
            text}, callback, asyncState);
    }
    
    public SearchResult EndSimpleQuery(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SearchResult)(results[0]));
    }
    
    /// <remarks>
    ///Full text Interface to Beagle
    ///</remarks>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gnome.org/projects/beagle/webservices/SimpleQuery2",RequestNamespace="http://www.gnome.org/projects/beagle/webservices",ResponseNamespace="http://www.gnome.org/projects/beagle/webservices",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public SearchResult SimpleQuery2(string text, string mimeType, string source, string queryDomain) {
        object[] results = this.Invoke("SimpleQuery2", new object[] {
            text,
            mimeType,
            source,
            queryDomain});
        return ((SearchResult)(results[0]));
    }
    
    public System.IAsyncResult BeginSimpleQuery2(string text, string mimeType, string source, string queryDomain, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SimpleQuery2", new object[] {
            text,
            mimeType,
            source,
            queryDomain}, callback, asyncState);
    }
    
    public SearchResult EndSimpleQuery2(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SearchResult)(results[0]));
    }
    
    /// <remarks>
    ///Common Interface to get more results from Beagle
    ///</remarks>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gnome.org/projects/beagle/webservices/GetMoreResults",RequestNamespace="http://www.gnome.org/projects/beagle/webservices",ResponseNamespace="http://www.gnome.org/projects/beagle/webservices",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public SearchResult GetResults(GetResultsRequest req) {
        object[] results = this.Invoke("GetResults", new object[] {
            req});
        return ((SearchResult)(results[0]));
    }
    
    public System.IAsyncResult BeginGetResults(GetResultsRequest req, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetResults", new object[] {
            req}, callback, asyncState);
    }
    
    public SearchResult EndGetResults(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SearchResult)(results[0]));
    }
    
    /// <remarks>
    ///Common Interface to get Snippets for results
    ///</remarks>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gnome.org/projects/beagle/webservices/GetSnippets",RequestNamespace="http://www.gnome.org/projects/beagle/webservices",ResponseNamespace="http://www.gnome.org/projects/beagle/webservices",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public HitSnippet[] GetSnippets(GetSnippetsRequest req) {
        object[] results = this.Invoke("GetSnippets", new object[] {
            req});
        return ((HitSnippet[])(results[0]));
    }
    
    public System.IAsyncResult BeginGetSnippets(GetSnippetsRequest req, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetSnippets", new object[] {
            req}, callback, asyncState);
    }
    
    public HitSnippet[] EndGetSnippets(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((HitSnippet[])(results[0]));
    }
}

/// <remarks/>
[Serializable()]
[System.Xml.Serialization.XmlType(Namespace="http://www.gnome.org/projects/beagle/webservices")]
public class SearchRequest {
    
    /// <remarks/>
    public string[] text;
    
    /// <remarks/>
    public string[] mimeType;
    
    /// <remarks/>
    public string[] searchSources;
    
    /// <remarks/>
    public QueryDomain qdomain;
    
    /// <remarks/>
    public int searchId;
    
    /// <remarks/>
    public int hopCount;
}

/*
/// <remarks/>
[Serializable()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gnome.org/projects/beagle/webservices")]
public enum QueryDomain {
    
    /// <remarks/>
    Local,
    
    /// <remarks/>
    System,
    
    /// <remarks/>
    Neighborhood,
    
    /// <remarks/>
    Global,
}
*/

/// <remarks/>
[Serializable()]
[System.Xml.Serialization.XmlType(Namespace="http://www.gnome.org/projects/beagle/webservices")]
public class SearchResult {
    
    /// <remarks/>
    public int statusCode;
    
    /// <remarks/>
    public string statusMsg;
    
    /// <remarks/>
    public string searchToken;
    
    /// <remarks/>
    public int firstResultIndex;
    
    /// <remarks/>
    public int numResults;
    
    /// <remarks/>
    public int totalResults;
    
    /// <remarks/>
    public HitResult[] hitResults;
}

/// <remarks/>
[Serializable()]
[System.Xml.Serialization.XmlType(Namespace="http://www.gnome.org/projects/beagle/webservices")]
public class HitResult {
    
    /// <remarks/>
    public string uri;
    
    /// <remarks/>
    public string resourceType;
    
    /// <remarks/>
    public string mimeType;
    
    /// <remarks/>
    public string source;
    
    /// <remarks/>
    public double score;
    
    /// <remarks/>
    public HitProperty[] properties;
    
    /// <remarks/>
    public int hashCode;
    
    /// <remarks/>
    public string snippet;
}

/// <remarks/>
[Serializable()]
[System.Xml.Serialization.XmlType(Namespace="http://www.gnome.org/projects/beagle/webservices")]
public class HitProperty {
    
    /// <remarks/>
    public string PKey;
    
    /// <remarks/>
    public string PVal;
    
    /// <remarks/>
    public bool IsMutable;
    
    /// <remarks/>
    public bool IsSearched;
}

/// <remarks/>
[Serializable()]
[System.Xml.Serialization.XmlType(Namespace="http://www.gnome.org/projects/beagle/webservices")]
public class GetResultsRequest {
    
    /// <remarks/>
    public string searchToken;
    
    /// <remarks/>
    public int startIndex;
}

/// <remarks/>
[Serializable()]
[System.Xml.Serialization.XmlType(Namespace="http://www.gnome.org/projects/beagle/webservices")]
public class GetSnippetsRequest {
    
    /// <remarks/>
    public string searchToken;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public int[] hitHashCodes;
}

/// <remarks/>
[Serializable()]
[System.Xml.Serialization.XmlType(Namespace="http://www.gnome.org/projects/beagle/webservices")]
public class HitSnippet {
    
    /// <remarks/>
    public int hashCode;
    
    /// <remarks/>
    public string snippet;
}

}
