#!/bin/sh

# This line will be automatically uncommented when you "make install"
#installed=1

if [ -z $installed ]; then
    CMD="./beagle-info"
else
    CMD="beagle-info"
fi

watch -n 5 $CMD --status
