.nh
.TH beagle-query 1
.SH NAME
beagle-query \- Search your personal information space
.SH SYNTAX
\f beagle-query\fR  [options...] <query string>
.SH DESCRIPTION
Insert a description here.

.SH OPTIONS
.TP
.B \--verbose
.IP 
Print detailed information about each hit.
.TP
.B \--mime \fImimetype\fP
.IP 
Constrain search results to this mime type.  This argument can be
specified multiple times.
.TP
.B \--source \fIsource\fP
.IP 

Constrain query to the specified search source.  A source list can be
obtained from the beagle-status command.
.SH AUTHOR
Novell, Inc.
.br
(dashboard-hackers@gnome.org)
