#!/bin/sh

# This line will be automatically uncommented when you "make install"
#installed=1

if [ -z $installed ]; then
    CMD="./beagle-info"
else
    CMD="beagle-info"
fi

while [ 1 ]; do
    str=`$CMD --status | head -n 20`
    clear
    echo "$str"
    # beagle-info causes a CPU spike, keep the hammering low
    sleep 5
done
